# Generated by Django 5.0.6 on 2024-06-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="online_user",
            name="user_id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
        ),
    ]
