# Generated by Django 5.0.6 on 2024-06-06 03:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("bank_app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Student",
        ),
    ]
