# Generated by Django 4.2.13 on 2024-06-06 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_alter_online_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='online_user',
            name='is_blacklisted',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.sys_manage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank_app.online_user')),
            ],
        ),
    ]
