# Generated by Django 5.0.6 on 2024-06-06 04:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank_app", "0002_delete_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="online_user",
            name="id",
        ),
        migrations.AddField(
            model_name="online_user",
            name="is_frozen",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="online_user",
            name="is_lost",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="online_user",
            name="password",
            field=models.CharField(default="666666", max_length=20),
        ),
        migrations.AddField(
            model_name="online_user",
            name="phone_num",
            field=models.CharField(default="10086", max_length=20),
        ),
        migrations.AddField(
            model_name="online_user",
            name="user_name",
            field=models.CharField(default="Unknown", max_length=20),
        ),
        migrations.AlterField(
            model_name="online_user",
            name="identity_card",
            field=models.CharField(max_length=18, primary_key=True, serialize=False),
        ),
    ]
