# Generated by Django 5.0.6 on 2024-06-10 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank_app", "0003_online_user_is_blacklisted_blacklist"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="identity_card",
            field=models.ForeignKey(
                db_column="identity_card",
                on_delete=django.db.models.deletion.PROTECT,
                to="bank_app.online_user",
                to_field="identity_card",
            ),
        ),
        migrations.AlterField(
            model_name="online_user",
            name="identity_card",
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
