# Generated by Django 5.0.6 on 2024-06-06 04:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank_app", "0003_remove_online_user_id_online_user_is_frozen_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="online_user",
            name="user_id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="online_user",
            name="identity_card",
            field=models.CharField(max_length=18),
        ),
    ]
