# Generated by Django 5.0.6 on 2024-06-11 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank_app", "0003_alter_account_identity_card"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blacklist",
            name="manager_id",
            field=models.ForeignKey(
                db_column="manager_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="bank_app.online_bank_manager",
            ),
        ),
        migrations.AlterField(
            model_name="blacklist",
            name="user_id",
            field=models.ForeignKey(
                db_column="user_id",
                on_delete=django.db.models.deletion.CASCADE,
                to="bank_app.online_user",
            ),
        ),
    ]
