# Generated by Django 5.0.6 on 2024-06-11 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank_app", "0004_alter_blacklist_manager_id_alter_blacklist_user_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blacklist",
            name="manager_id",
        ),
        migrations.AddField(
            model_name="blacklist",
            name="online_bank_manager_id",
            field=models.ForeignKey(
                db_column="online_bank_manager_id",
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="bank_app.online_bank_manager",
            ),
        ),
    ]
