# Generated by Django 5.0.6 on 2024-06-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bank_app", "0004_alter_account_identity_card_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="online_user",
            name="user_id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
