# Generated by Django 5.0.6 on 2024-06-11 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0005_remove_blacklist_manager_id_and_more'),
    ]

    operations = [
    ]
