# Generated by Django 5.0.6 on 2024-06-11 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0006_auto_20240611_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='bank_app.online_user'),
        ),
        migrations.AlterField(
            model_name='account',
            name='identity_card',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
