# Generated by Django 5.0.6 on 2024-06-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0007_account_user_id_alter_account_identity_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='phone_num',
            field=models.CharField(default='10086', max_length=20),
        ),
    ]
