# Generated by Django 5.0.6 on 2024-06-11 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0008_account_phone_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='identity_card',
            field=models.CharField(max_length=18),
        ),
    ]
