# Generated by Django 5.0.6 on 2024-05-26 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counteropt', '0003_alter_account_account_id_alter_cashier_cashier_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashier',
            old_name='trade_authortiy',
            new_name='trade_authority',
        ),
    ]
